### ISSUE TITLE
API nbs

### ISSUE THREAD

**Issue by GAECLab** [GAECLab/NR491_Fall2022#6]
Quick Qs: @vperin as I'm merging the API branch to main:
1. Is the ".shift(4, freq='H')" needed here? daily_mean_values = daily_mean.df('q').shift(4, freq='H')?
2. I see that in the end of the planet_api notebook you have 85 items to download whereas I get 5 items to download, any thoughts on the difference?

**Comment by vperin** [comment]
1. Not necessary. I made de the changes and committed.
2. That is because of the dates that we have in the notebook (only for one 1 day). To download the data for Mollie, I used a different interval (a month if I am not wrong).

**Comment by GAECLab** [comment]
Ok, thx, Vini
